apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          replicaCount: 2
          service:
          nodeSelector:
            topology.kubernetes.io/region: {{ .region }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
